[input]
topfile = "../inputs/apoa1/top_all27_prot_lipid.rtf"
parfile = "../inputs/apoa1/par_all27_prot_lipid.prm"
psffile = "../inputs/apoa1/apoa1.psf"
pdbfile = "../inputs/apoa1/apoa1.pdb"
rstfile = "../inputs/apoa1/apoa1.rst"

[energy]
forcefield = "CHARMM"
electrostatic = "PME"
pme_scheme = ["OPT_1DALLTOALL", "OPT_2DALLTOALL", "NOOPT_1DALLTOALL", "NOOPT_2DALLTOALL"]
switchdist = 10.0
cutoffdist = 12.0
pairlistdist = 13.5
pme_alpha = 0.34
pme_ngrid_x = 80
pme_ngrid_y = 80
pme_ngrid_z = 64
pme_nspline = 4
nonbond_kernel = ["GENERIC", "FUGAKU", "INTEL"]

[dynamics]
integrator = "VVER"
nsteps = 10000
timestep = 0.002
eneout_period = 100
nbupdate_period = 10

[constraints]
rigid_bond = "YES"

[ensemble]
ensemble = "NPT"
tpcontrol = "BUSSI"
pressure = 1.0
temperature = 300.0
group_tp = "YES"

[boundary]
type = "PBC"
domain_x = [2, 4]
domain_y = [2, 4]
domain_z = [1, 2, 4]

[job]
node_cpus = 56
compiler = "GNU"
time = 01:00:00
bin = "../../src/spdyn/spdyn"
nodes = [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
mpis = [1, 2, 4, 8]
omps = [7, 14, 28, 56]
