[input]
grotopfile = "../../inputs/hero11+tdp43/topol.top"
grocrdfile = "../../inputs/hero11+tdp43/crd/hero11_tdp43_solv_ions_em1.gro"
rstfile = "../../inputs/hero11+tdp43/hero11_tdp43_npt3.rst"

[energy]
forcefield = "GROAMBER"
electrostatic = "PME"
switchdist = 10.0
cutoffdist = 10.0
pairlistdist = 12.0
pme_nspline = [8, 4]
pme_ngrid_x = [256, 512]
pme_ngrid_y = [256, 512]
pme_ngrid_z = [256, 512]
pme_scheme = ["OPT_1DALLTOALL", "OPT_2DALLTOALL"]
nonbond_kernel = ["INTEL", "GPU"]

[dynamics]
integrator = ["VRES"]
nsteps = [4800]
timestep = [0.0035]
elec_long_period = [2]
thermostat_period = [6]
barostat_period = [6]
nbupdate_period = [6]
eneout_period = 120
stoptr_period = 6

[constraints]
rigid_bond = "YES"
hydrogen_type = "mass"
fast_water = "YES"
water_model = "SOL"
hydrogen_mass_upper_bound = 2.0

[ensemble]
ensemble = "NPT"
tpcontrol = "BUSSI"
temperature = 300.0
pressure = 1.0
tau_p = 10.0


[boundary]
type = "PBC"
domain_x = [8, 16, 32]
domain_y = [8, 16, 16]
domain_z = [4, 8, 16]

[job]
node_cpus = 56
compiler = "CRAY"
time = 01:00:00
bin = "../../../src/spdyn/spdyn"
nodes = [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
mpis = [8]
omps = [7]
